services:
  kanecta-api:
    image: cloudsculptors/kanecta-api:latest
    build:
      context: ./kanecta-api
    ports:
      - "3000:3000"
    volumes:
      - ./kanecta-datastore:/datastore
    environment:
      - KANECTA_DATASTORE=/datastore

  kanecta-client:
    image: cloudsculptors/kanecta-web-client:latest
    build:
      context: ./kanecta-client-web
    ports:
      - "8080:80"
    depends_on:
      - kanecta-api
