-- Seed public site pages for the 14 newly activated home page categories.
-- owner_type = 'site', public = true. Content is placeholder — edit via the UI.

INSERT INTO pages (slug, title, content_json, owner_type, owner_id, public, created_by_id, created_by_name)
VALUES
  ('buy-sell-swap',       'Buy, Sell & Swap',         '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Buy, sell, swap, or give away items locally.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',        'site', null, true, 'system', 'System'),
  ('visitor-activities',  'Visitor Activities',        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Things to do and see in Featherston and the South Wairarapa.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',  'site', null, true, 'system', 'System'),
  ('health-wellbeing',    'Health & Wellbeing',        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"GPs, pharmacy, dentist, mental health, and healthcare access in Featherston.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',  'site', null, true, 'system', 'System'),
  ('sport-recreation',    'Sport & Recreation',        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Sports clubs, facilities, courts, and fitness groups.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',  'site', null, true, 'system', 'System'),
  ('environment-outdoors','Environment & Outdoors',    '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Remutaka Rail Trail, Lake Wairarapa, conservation, and local walks.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}','site', null, true, 'system', 'System'),
  ('arts-culture',        'Arts & Culture',            '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Local artists, galleries, Booktown festival, and performances.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',        'site', null, true, 'system', 'System'),
  ('food-drink',          'Food & Drink',              '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Cafes, restaurants, local producers, and farmers markets.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',          'site', null, true, 'system', 'System'),
  ('jobs-volunteering',   'Jobs & Volunteering',       '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Local employment opportunities and ways to contribute your skills.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',   'site', null, true, 'system', 'System'),
  ('property-housing',    'Property & Housing',        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Rentals, real estate, and local housing information.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',    'site', null, true, 'system', 'System'),
  ('youth',               'Youth',                     '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Services, activities, and resources for young people in Featherston.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',               'site', null, true, 'system', 'System'),
  ('seniors',             'Seniors',                   '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Services, activities, and support for older residents.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',             'site', null, true, 'system', 'System'),
  ('pets-animals',        'Pets & Animals',            '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Vets, lost pets, and animal services in the area.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',        'site', null, true, 'system', 'System'),
  ('local-accommodation', 'Local Accommodation',       '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Places to stay in and around Featherston.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}', 'site', null, true, 'system', 'System'),
  ('history',             'History',                   '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"The history of Featherston and the surrounding district.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',             'site', null, true, 'system', 'System')
ON CONFLICT (slug) DO NOTHING;
